// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZrnb7Dxf95z_KtYH_syS9usGJqbiZYzI',
    appId: '1:521950457583:web:190e01069d91c2c207751a',
    messagingSenderId: '521950457583',
    projectId: 'gotilo-5a831',
    authDomain: 'gotilo-5a831.firebaseapp.com',
    storageBucket: 'gotilo-5a831.firebasestorage.app',
    measurementId: 'G-5PZ9L14CF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuk3axHMy5NBBTALfQxRTHOsbjVnQ2iG4',
    appId: '1:521950457583:android:963b5c00daef1d7107751a',
    messagingSenderId: '521950457583',
    projectId: 'gotilo-5a831',
    storageBucket: 'gotilo-5a831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDXWinqEs7ihN7zjhEFuK5KHKuPTVW_Y',
    appId: '1:521950457583:ios:bd6547509215588a07751a',
    messagingSenderId: '521950457583',
    projectId: 'gotilo-5a831',
    storageBucket: 'gotilo-5a831.firebasestorage.app',
    iosBundleId: 'com.example.gotiloNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDXWinqEs7ihN7zjhEFuK5KHKuPTVW_Y',
    appId: '1:521950457583:ios:bd6547509215588a07751a',
    messagingSenderId: '521950457583',
    projectId: 'gotilo-5a831',
    storageBucket: 'gotilo-5a831.firebasestorage.app',
    iosBundleId: 'com.example.gotiloNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZrnb7Dxf95z_KtYH_syS9usGJqbiZYzI',
    appId: '1:521950457583:web:1d3c6c42e76ad6ef07751a',
    messagingSenderId: '521950457583',
    projectId: 'gotilo-5a831',
    authDomain: 'gotilo-5a831.firebaseapp.com',
    storageBucket: 'gotilo-5a831.firebasestorage.app',
    measurementId: 'G-YDH2RMH750',
  );
}
